# Run `travis lint` when changing this file to avoid breaking the build.

cache:
  directories:
    - $HOME/.m2

language: java

jdk: openjdk11

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw install -DskipTests=true -Dlicense.skip=true -Dmaven.javadoc.skip=true -B -V
script: ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/e57478303f87ecd7bffc
    on_success: change
    on_failure: always

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "KgsDLBeq73Ml4DgixnG9Nb/P7aaUEAbvtVQo+9piDfNeYRzaBk0t7B8kX5kXVahEmd1aybhNW11ImruKy582ycTyg9X4lbIMG8NOG2XzqscFxNuHRpbGsisWvH/DuHtY5K+wVohfkXNwip5no0LDoaAUOBNQz1VLCz49ToqhSElNOcHCPTgrmCMSy5RPwSd29ug+YxyYLqH3NP52CWtL+tfVs6zxvEf1EaVMIlE13DEfLDqX45nfrKDhuQFJn659zw3YnN0VcfS/UlxdGb26cBEukk0oq8hehT78Fb0dK5X4Ecdu8eIoE/RBY4Vk12mH+ZlThgmCl7Z+jRxJN40hKRnc76ZKOSJKZ6PEfC3efsZuI0FxlZwbCoV3zWH3+jdCnFZkHOgOtq8ghCETPqBX8SZz+4zmydSxomp7VhsMeNZ5EkLAWiA5l/RWBTUro1eYIwuR5XgxRwmsDpm/7+VCDLWKw/6E9zLrPKBfCbdCEBLZI4NpNJm83izL3nGd/oQNbTtrr/JW0bj2yYAM84FC8529aLVYRLufPfgWrbXfinwYxCl+5557ykKq6ALl5cOVgo+PawMWC00xV/NjZjqzsCFzArTyjjYRp3DPbPSJINkTX11ebyWcAC+GlD8MWc+n0UKzURDn6JGyFxluv8uZQTfYrNcTA4Or/HbKF6ezAtU="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "mI+3m0MswNKCZTzna5HFW//4Y6tKCeEBPogJc9LqIekYq7cCqIiBvP8VHXX53PnkdUHBhRHK7K/0X6HX0dUUKA7FLflcg1ZYsVqm78U4I05CPoztYULbT7Q+1p1j8ykMY6GWERL7vutRe64T9WHTj6TAXk3C0heJcSlKR/SEEloD8NaeEaMGRY6QUH8rpJGeFB6FVhO0fOCDDxQfjtxrFzUmxnFmmVampCzdcVuy6ga6AOdzk4wNvm+FVDKkhqEooj55kW45mu4XyJdZM2JGxVt4Vr18uKnrOe1QYrZ3PGTfcn+fvlXKNx6UiM8tBgSefyNgdpv6SvL9E8Da0hvabMR7EOx7BKxCZrxTDto8pL0FaompD9Gw82GConNatw/fOvkmQK7qg4O3w4zD4c0MpHbaQV+rU8zpznn0obSx9EMbl94XNrRFyYi6VtYx8MDw9m69yQShlfw5aZs71YLAXlCoAflOWCBLJukkVp4nIiUqZb3L6NS8Eyq81VTLuk9d7L+KGcTf7Io6w1Iw0Y3FJglrFM56+Oh+PGeh3rBkB/9pQNhG4FtsYdArhdxjRpbU73KPKLwhPFidgpL0KjUEI2DeuaR6dwGKFLPoFQsgFzQ8KrB7JCQdlDGiuGCiXp0NbCtUbjrc2iLXj9et/DeTuhsw6dtJ6CONUiBh+fhwexM="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "eUyTKQ+sFPNk5T+adX3zhMzbCeaizJJQdKnSdHHF0h/IAI/NXXymmFTdppzxTuFFAOudUqxXhst39QEM/k6wJeNN3lo9cNfcO4wGsOrLYmtY6npFhJX5Vs/KozwdxztNRVbso8xfsKl9YJ8IFnquun4d9X8yVIABwz5Xi237CBQxQF7hZxiSeVUGcjXLW6psfICNJ/1W0EuHKE5hiNjzVQD13VVcYsDCDcxNRHPvQmRVj5KP4rWIBazxZSA/RxYdIBHy73t3+tHSJP7ynalVbCNeFfZXdFEjkDADI81EJzLz7RnSE2QzhNpg+yW0Vcp9Ar3SPGv7PVSWPpVr4JsSjDbQ54RKlHw0GioMMGuWL2OV8BgBkbE/PJeQlYNGFUsL1f2VlMUv5j6i9ZhY591vbU7Rk3PxfxLE+IEl+PWMRUx7YPBl3w4wvJjpFr/jwHvqI32ixR84pPEPmlhuZLd+3pX1O23RM6AT221qCfM2NUEc0gmWF7BFOtAVCCqQd9xtrBFZ6Cymhwm1Ai8u4aqlo0uwdZI9TBxjmFu4w2hmMkQlPleLdV9ZnedEImKJeR1n/ghtFCK8DeKoVvDHySmo4FjLYmOGALAN13Mk+3EgyjD91NcvSswi5u5vKt62xY+zq1hfTbXU9b97JU05KyKQJB3/HFFulu6cWCL6OZ0Jx7U="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "NU0KHmgQNWUxrDasWn9i9jg8eVK1u8OMV1yQ0ykxn+FNgDB7l7dk03kOPb/qwtOdPTbu18fltMrEELBh7sMp09E2NrOHOKu6rdgCxTjcueMPO5GPUAUfEcUE6RkQhiCEK4sXC4rGN0YBGhE//NXZhd71hseoP8Mg0ldXqxW4bO9StMneI3qoibmZteGrTUv/IsTsUew2R/4ZgGeELteOrzQtUUZ8XTs4kYtDAC620TzvEkykFiCn3pNpB57XIHjiY7HPltkBF5Zg9de60X3wxF4g/v7SUNdF0wMhtFmB1rHw6FrANdZccmNtM7HlPUwW1OGlBFEDdZ0XN7lhqRQHROQR3PdYNyVnuPOpW8sKljdL+bJWgcDXjhvP1dzKwPl5o++Y0z3MerT2JU154wSLgtMuVA0rcHmmbZ6eNolqAU9tnjiB72u6FZ4oO4j1bViKDKw5u0zPV0ZEN5TyY7a8Hj/EUV/qASgYX3r4w3kSusww0XSQV+uj0Jlo4vKRMAfaChZjdO/+0opwTjwhFCYrG3v5Ddu+JT52r1KlhByAwHit1gxEPu0o74Jb4rN3Yr1PvN38dCskd70VCZh3dqZ4pO0WxyVHOjTocAhnupVAFVdZbNBiwAPjMSCcvSdecE2+997D8denEmoz80ymDbkM9SytV5ptsdONA4c+Zay654Q="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "IOTWlosiuyF3zidWkC2Bmfo/oaQQyFVwAnEKHdxSSslnqJOWcBwMshUxZVADz2bmb7s/wyItkqivUZ5Pk0N/yRFrJl98hf1+XfBxumFq48stfTr9I8i5IaJRFAWOuC8ZCdv4YYtneRSymKJO0thEyIqghVMfuvW5AUR/o1x+9Lmjd5SnEJvdGKYVegp3yFCt0j+oEELbSB1cL3CWG39FPoc8VAWgNEpa6NLWDMO/EQSY/jcfLzBPMys0FBCKqgUtXn4/1vo9k9/i2F51x44kuVvt2wLJzOY004qFqRyxboH1bk1U9bCrQ8WIpnLkhLzyz0hJPFv3WJthIwKCtFrBoX/SIj+qwUIcFtdV9n59DQojbXCdqT72vCTGyC0nEYV4JXhshONu2qaz69sr6Mvd3gNo9bowr9q25c/l12YyQeyX3ep2QVy+RY0JTyqprgE/S9n+gjRQq3xJtc0rIP/54KV4eq6w+0xTXKVO0vp9ijlyMPWSYMsoBUmVzIibyLpJhNpbrfw2n0vc1fJWrOfrjEW3SX2ud/ta+qAqTaWDsuHMqhyjz1l2TJ11yxJQrdcph737uNfegN3IyPOK87bZvkYvwNL1uwSFGkxje4ylxT9PoHbr/2JFGMlVYhro3/qlqOg8d9v+4JELKtb1WNJ+HfgmBoc2kJB+MRf7jhfEZF4="
